### PR TITLE
:wrench: remove default port 3000 hardcoded

### LINKED ISSUE #133: Change default port to ????
Nullstack is crashing in some macbooks because port 5000 is taken, should we move to port 3000 like normies or do something else?

ಥ_ಥ i liked 5000

### PR DESCRIPTION
**Pull request by MarceloBorgesP**
resolves #133

### CODE REVIEW

File: server/server.js [hunk 1]
```diff
@@ -25,7 +25,11 @@ if (!global.fetch) {
 
 const app = express();
 const server = http.createServer(app);
-server.port = process.env['NULLSTACK_SERVER_PORT'] || process.env['PORT'] || 5000;
+server.port = process.env['NULLSTACK_SERVER_PORT'] || process.env['PORT'];
```
Comment (Mortaro) [inline server/server.js:28]: We should only force ports when !server.less as well, since hosts like vercel will not work with nullstack internal port anyway

**Review by Mortaro — CHANGES_REQUESTED** [review]
